<?php
$server = "localhost";

// github
/*
$user = "someU";
global $pwd;
// $pwd = "someP"; // production
 $pwd = "someP"; // local
global $db;
$db = "someDb";
*/

// local
/*
$user = "root";
global $pwd;
// $pwd = "gohome"; // production
 $pwd = "gohomE1k"; // local
global $db;
$db = "kronus";
*/

// production

$user = "root";
global $pwd;
 $pwd = "gohome"; // production
// $pwd = "gohomE1k"; // local
global $db;
$db = "kronus";

?>
